/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FrRouteImport } from './routes/fr'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as FrAboutRouteImport } from './routes/fr.about'
import { Route as FrBlogRouteImport } from './routes/fr.blog'
import { Route as FrClaimsRouteImport } from './routes/fr.claims'
import { Route as FrContactRouteImport } from './routes/fr.contact'
import { Route as FrPrivacyRouteImport } from './routes/fr.privacy'
import { Route as FrServicesRouteImport } from './routes/fr.services'
import { Route as FrTermsRouteImport } from './routes/fr.terms'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as LocationsFortLauderdaleRouteImport } from './routes/locations.fort-lauderdale'
import { Route as LocationsMiamiRouteImport } from './routes/locations.miami'
import { Route as LocationsNaplesRouteImport } from './routes/locations.naples'
import { Route as LocationsOrlandoRouteImport } from './routes/locations.orlando'
import { Route as LocationsPensacolaRouteImport } from './routes/locations.pensacola'
import { Route as LocationsTampaRouteImport } from './routes/locations.tampa'
import { Route as LocationsWestPalmBeachRouteImport } from './routes/locations.west-palm-beach'
import { Route as ProfessionalServicesIndexRouteImport } from './routes/professional-services.index'
import { Route as ProfessionalServicesAppraisalRouteImport } from './routes/professional-services.appraisal'
import { Route as ProfessionalServicesExpertWitnessRouteImport } from './routes/professional-services.expert-witness'
import { Route as ProfessionalServicesUmpireRouteImport } from './routes/professional-services.umpire'
import { Route as BlogCategoryCategoryRouteImport } from './routes/blog.category.$category'
import { Route as BlogPage2RouteImport } from './routes/blog.page.2'
import { Route as BlogPage3RouteImport } from './routes/blog.page.3'
import { Route as FrLocationsIndexRouteImport } from './routes/fr.locations.index'
import { Route as FrLocationsFortLauderdaleRouteImport } from './routes/fr.locations.fort-lauderdale'
import { Route as FrLocationsMiamiRouteImport } from './routes/fr.locations.miami'
import { Route as FrLocationsNaplesRouteImport } from './routes/fr.locations.naples'
import { Route as FrLocationsOrlandoRouteImport } from './routes/fr.locations.orlando'
import { Route as FrLocationsPensacolaRouteImport } from './routes/fr.locations.pensacola'
import { Route as FrLocationsTampaRouteImport } from './routes/fr.locations.tampa'
import { Route as FrLocationsWestPalmBeachRouteImport } from './routes/fr.locations.west-palm-beach'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const FrAboutRoute = FrAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => FrRoute,
} as any)
const FrBlogRoute = FrBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => FrRoute,
} as any)
const FrClaimsRoute = FrClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => FrRoute,
} as any)
const FrContactRoute = FrContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => FrRoute,
} as any)
const FrPrivacyRoute = FrPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => FrRoute,
} as any)
const FrServicesRoute = FrServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => FrRoute,
} as any)
const FrTermsRoute = FrTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => FrRoute,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsFortLauderdaleRoute = LocationsFortLauderdaleRouteImport.update({
  id: '/locations/fort-lauderdale',
  path: '/locations/fort-lauderdale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsMiamiRoute = LocationsMiamiRouteImport.update({
  id: '/locations/miami',
  path: '/locations/miami',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsNaplesRoute = LocationsNaplesRouteImport.update({
  id: '/locations/naples',
  path: '/locations/naples',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsOrlandoRoute = LocationsOrlandoRouteImport.update({
  id: '/locations/orlando',
  path: '/locations/orlando',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsPensacolaRoute = LocationsPensacolaRouteImport.update({
  id: '/locations/pensacola',
  path: '/locations/pensacola',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsTampaRoute = LocationsTampaRouteImport.update({
  id: '/locations/tampa',
  path: '/locations/tampa',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsWestPalmBeachRoute = LocationsWestPalmBeachRouteImport.update({
  id: '/locations/west-palm-beach',
  path: '/locations/west-palm-beach',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalServicesIndexRoute =
  ProfessionalServicesIndexRouteImport.update({
    id: '/professional-services/',
    path: '/professional-services/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfessionalServicesAppraisalRoute =
  ProfessionalServicesAppraisalRouteImport.update({
    id: '/professional-services/appraisal',
    path: '/professional-services/appraisal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfessionalServicesExpertWitnessRoute =
  ProfessionalServicesExpertWitnessRouteImport.update({
    id: '/professional-services/expert-witness',
    path: '/professional-services/expert-witness',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfessionalServicesUmpireRoute =
  ProfessionalServicesUmpireRouteImport.update({
    id: '/professional-services/umpire',
    path: '/professional-services/umpire',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCategoryCategoryRoute = BlogCategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => BlogRoute,
} as any)
const BlogPage2Route = BlogPage2RouteImport.update({
  id: '/page/2',
  path: '/page/2',
  getParentRoute: () => BlogRoute,
} as any)
const BlogPage3Route = BlogPage3RouteImport.update({
  id: '/page/3',
  path: '/page/3',
  getParentRoute: () => BlogRoute,
} as any)
const FrLocationsIndexRoute = FrLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => FrRoute,
} as any)
const FrLocationsFortLauderdaleRoute =
  FrLocationsFortLauderdaleRouteImport.update({
    id: '/locations/fort-lauderdale',
    path: '/locations/fort-lauderdale',
    getParentRoute: () => FrRoute,
  } as any)
const FrLocationsMiamiRoute = FrLocationsMiamiRouteImport.update({
  id: '/locations/miami',
  path: '/locations/miami',
  getParentRoute: () => FrRoute,
} as any)
const FrLocationsNaplesRoute = FrLocationsNaplesRouteImport.update({
  id: '/locations/naples',
  path: '/locations/naples',
  getParentRoute: () => FrRoute,
} as any)
const FrLocationsOrlandoRoute = FrLocationsOrlandoRouteImport.update({
  id: '/locations/orlando',
  path: '/locations/orlando',
  getParentRoute: () => FrRoute,
} as any)
const FrLocationsPensacolaRoute = FrLocationsPensacolaRouteImport.update({
  id: '/locations/pensacola',
  path: '/locations/pensacola',
  getParentRoute: () => FrRoute,
} as any)
const FrLocationsTampaRoute = FrLocationsTampaRouteImport.update({
  id: '/locations/tampa',
  path: '/locations/tampa',
  getParentRoute: () => FrRoute,
} as any)
const FrLocationsWestPalmBeachRoute =
  FrLocationsWestPalmBeachRouteImport.update({
    id: '/locations/west-palm-beach',
    path: '/locations/west-palm-beach',
    getParentRoute: () => FrRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/claims': typeof ClaimsRoute
  '/contact': typeof ContactRoute
  '/fr': typeof FrRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/blog': typeof FrBlogRoute
  '/fr/claims': typeof FrClaimsRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/privacy': typeof FrPrivacyRoute
  '/fr/services': typeof FrServicesRoute
  '/fr/terms': typeof FrTermsRoute
  '/locations/fort-lauderdale': typeof LocationsFortLauderdaleRoute
  '/locations/miami': typeof LocationsMiamiRoute
  '/locations/naples': typeof LocationsNaplesRoute
  '/locations/orlando': typeof LocationsOrlandoRoute
  '/locations/pensacola': typeof LocationsPensacolaRoute
  '/locations/tampa': typeof LocationsTampaRoute
  '/locations/west-palm-beach': typeof LocationsWestPalmBeachRoute
  '/professional-services/appraisal': typeof ProfessionalServicesAppraisalRoute
  '/professional-services/expert-witness': typeof ProfessionalServicesExpertWitnessRoute
  '/professional-services/umpire': typeof ProfessionalServicesUmpireRoute
  '/locations/': typeof LocationsIndexRoute
  '/professional-services/': typeof ProfessionalServicesIndexRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/blog/page/2': typeof BlogPage2Route
  '/blog/page/3': typeof BlogPage3Route
  '/fr/locations/fort-lauderdale': typeof FrLocationsFortLauderdaleRoute
  '/fr/locations/miami': typeof FrLocationsMiamiRoute
  '/fr/locations/naples': typeof FrLocationsNaplesRoute
  '/fr/locations/orlando': typeof FrLocationsOrlandoRoute
  '/fr/locations/pensacola': typeof FrLocationsPensacolaRoute
  '/fr/locations/tampa': typeof FrLocationsTampaRoute
  '/fr/locations/west-palm-beach': typeof FrLocationsWestPalmBeachRoute
  '/fr/locations/': typeof FrLocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/claims': typeof ClaimsRoute
  '/contact': typeof ContactRoute
  '/fr': typeof FrRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/blog': typeof FrBlogRoute
  '/fr/claims': typeof FrClaimsRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/privacy': typeof FrPrivacyRoute
  '/fr/services': typeof FrServicesRoute
  '/fr/terms': typeof FrTermsRoute
  '/locations/fort-lauderdale': typeof LocationsFortLauderdaleRoute
  '/locations/miami': typeof LocationsMiamiRoute
  '/locations/naples': typeof LocationsNaplesRoute
  '/locations/orlando': typeof LocationsOrlandoRoute
  '/locations/pensacola': typeof LocationsPensacolaRoute
  '/locations/tampa': typeof LocationsTampaRoute
  '/locations/west-palm-beach': typeof LocationsWestPalmBeachRoute
  '/professional-services/appraisal': typeof ProfessionalServicesAppraisalRoute
  '/professional-services/expert-witness': typeof ProfessionalServicesExpertWitnessRoute
  '/professional-services/umpire': typeof ProfessionalServicesUmpireRoute
  '/locations': typeof LocationsIndexRoute
  '/professional-services': typeof ProfessionalServicesIndexRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/blog/page/2': typeof BlogPage2Route
  '/blog/page/3': typeof BlogPage3Route
  '/fr/locations/fort-lauderdale': typeof FrLocationsFortLauderdaleRoute
  '/fr/locations/miami': typeof FrLocationsMiamiRoute
  '/fr/locations/naples': typeof FrLocationsNaplesRoute
  '/fr/locations/orlando': typeof FrLocationsOrlandoRoute
  '/fr/locations/pensacola': typeof FrLocationsPensacolaRoute
  '/fr/locations/tampa': typeof FrLocationsTampaRoute
  '/fr/locations/west-palm-beach': typeof FrLocationsWestPalmBeachRoute
  '/fr/locations': typeof FrLocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/claims': typeof ClaimsRoute
  '/contact': typeof ContactRoute
  '/fr': typeof FrRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/blog': typeof FrBlogRoute
  '/fr/claims': typeof FrClaimsRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/privacy': typeof FrPrivacyRoute
  '/fr/services': typeof FrServicesRoute
  '/fr/terms': typeof FrTermsRoute
  '/locations/fort-lauderdale': typeof LocationsFortLauderdaleRoute
  '/locations/miami': typeof LocationsMiamiRoute
  '/locations/naples': typeof LocationsNaplesRoute
  '/locations/orlando': typeof LocationsOrlandoRoute
  '/locations/pensacola': typeof LocationsPensacolaRoute
  '/locations/tampa': typeof LocationsTampaRoute
  '/locations/west-palm-beach': typeof LocationsWestPalmBeachRoute
  '/professional-services/appraisal': typeof ProfessionalServicesAppraisalRoute
  '/professional-services/expert-witness': typeof ProfessionalServicesExpertWitnessRoute
  '/professional-services/umpire': typeof ProfessionalServicesUmpireRoute
  '/locations/': typeof LocationsIndexRoute
  '/professional-services/': typeof ProfessionalServicesIndexRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/blog/page/2': typeof BlogPage2Route
  '/blog/page/3': typeof BlogPage3Route
  '/fr/locations/fort-lauderdale': typeof FrLocationsFortLauderdaleRoute
  '/fr/locations/miami': typeof FrLocationsMiamiRoute
  '/fr/locations/naples': typeof FrLocationsNaplesRoute
  '/fr/locations/orlando': typeof FrLocationsOrlandoRoute
  '/fr/locations/pensacola': typeof FrLocationsPensacolaRoute
  '/fr/locations/tampa': typeof FrLocationsTampaRoute
  '/fr/locations/west-palm-beach': typeof FrLocationsWestPalmBeachRoute
  '/fr/locations/': typeof FrLocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/claims'
    | '/contact'
    | '/fr'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/blog/$slug'
    | '/fr/about'
    | '/fr/blog'
    | '/fr/claims'
    | '/fr/contact'
    | '/fr/privacy'
    | '/fr/services'
    | '/fr/terms'
    | '/locations/fort-lauderdale'
    | '/locations/miami'
    | '/locations/naples'
    | '/locations/orlando'
    | '/locations/pensacola'
    | '/locations/tampa'
    | '/locations/west-palm-beach'
    | '/professional-services/appraisal'
    | '/professional-services/expert-witness'
    | '/professional-services/umpire'
    | '/locations/'
    | '/professional-services/'
    | '/blog/category/$category'
    | '/blog/page/2'
    | '/blog/page/3'
    | '/fr/locations/fort-lauderdale'
    | '/fr/locations/miami'
    | '/fr/locations/naples'
    | '/fr/locations/orlando'
    | '/fr/locations/pensacola'
    | '/fr/locations/tampa'
    | '/fr/locations/west-palm-beach'
    | '/fr/locations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/claims'
    | '/contact'
    | '/fr'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/blog/$slug'
    | '/fr/about'
    | '/fr/blog'
    | '/fr/claims'
    | '/fr/contact'
    | '/fr/privacy'
    | '/fr/services'
    | '/fr/terms'
    | '/locations/fort-lauderdale'
    | '/locations/miami'
    | '/locations/naples'
    | '/locations/orlando'
    | '/locations/pensacola'
    | '/locations/tampa'
    | '/locations/west-palm-beach'
    | '/professional-services/appraisal'
    | '/professional-services/expert-witness'
    | '/professional-services/umpire'
    | '/locations'
    | '/professional-services'
    | '/blog/category/$category'
    | '/blog/page/2'
    | '/blog/page/3'
    | '/fr/locations/fort-lauderdale'
    | '/fr/locations/miami'
    | '/fr/locations/naples'
    | '/fr/locations/orlando'
    | '/fr/locations/pensacola'
    | '/fr/locations/tampa'
    | '/fr/locations/west-palm-beach'
    | '/fr/locations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/claims'
    | '/contact'
    | '/fr'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/blog/$slug'
    | '/fr/about'
    | '/fr/blog'
    | '/fr/claims'
    | '/fr/contact'
    | '/fr/privacy'
    | '/fr/services'
    | '/fr/terms'
    | '/locations/fort-lauderdale'
    | '/locations/miami'
    | '/locations/naples'
    | '/locations/orlando'
    | '/locations/pensacola'
    | '/locations/tampa'
    | '/locations/west-palm-beach'
    | '/professional-services/appraisal'
    | '/professional-services/expert-witness'
    | '/professional-services/umpire'
    | '/locations/'
    | '/professional-services/'
    | '/blog/category/$category'
    | '/blog/page/2'
    | '/blog/page/3'
    | '/fr/locations/fort-lauderdale'
    | '/fr/locations/miami'
    | '/fr/locations/naples'
    | '/fr/locations/orlando'
    | '/fr/locations/pensacola'
    | '/fr/locations/tampa'
    | '/fr/locations/west-palm-beach'
    | '/fr/locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ClaimsRoute: typeof ClaimsRoute
  ContactRoute: typeof ContactRoute
  FrRoute: typeof FrRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  LocationsFortLauderdaleRoute: typeof LocationsFortLauderdaleRoute
  LocationsMiamiRoute: typeof LocationsMiamiRoute
  LocationsNaplesRoute: typeof LocationsNaplesRoute
  LocationsOrlandoRoute: typeof LocationsOrlandoRoute
  LocationsPensacolaRoute: typeof LocationsPensacolaRoute
  LocationsTampaRoute: typeof LocationsTampaRoute
  LocationsWestPalmBeachRoute: typeof LocationsWestPalmBeachRoute
  ProfessionalServicesAppraisalRoute: typeof ProfessionalServicesAppraisalRoute
  ProfessionalServicesExpertWitnessRoute: typeof ProfessionalServicesExpertWitnessRoute
  ProfessionalServicesUmpireRoute: typeof ProfessionalServicesUmpireRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  ProfessionalServicesIndexRoute: typeof ProfessionalServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/fr/about': {
      id: '/fr/about'
      path: '/about'
      fullPath: '/fr/about'
      preLoaderRoute: typeof FrAboutRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/blog': {
      id: '/fr/blog'
      path: '/blog'
      fullPath: '/fr/blog'
      preLoaderRoute: typeof FrBlogRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/claims': {
      id: '/fr/claims'
      path: '/claims'
      fullPath: '/fr/claims'
      preLoaderRoute: typeof FrClaimsRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/contact': {
      id: '/fr/contact'
      path: '/contact'
      fullPath: '/fr/contact'
      preLoaderRoute: typeof FrContactRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/privacy': {
      id: '/fr/privacy'
      path: '/privacy'
      fullPath: '/fr/privacy'
      preLoaderRoute: typeof FrPrivacyRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/services': {
      id: '/fr/services'
      path: '/services'
      fullPath: '/fr/services'
      preLoaderRoute: typeof FrServicesRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/terms': {
      id: '/fr/terms'
      path: '/terms'
      fullPath: '/fr/terms'
      preLoaderRoute: typeof FrTermsRouteImport
      parentRoute: typeof FrRoute
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/fort-lauderdale': {
      id: '/locations/fort-lauderdale'
      path: '/locations/fort-lauderdale'
      fullPath: '/locations/fort-lauderdale'
      preLoaderRoute: typeof LocationsFortLauderdaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/miami': {
      id: '/locations/miami'
      path: '/locations/miami'
      fullPath: '/locations/miami'
      preLoaderRoute: typeof LocationsMiamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/naples': {
      id: '/locations/naples'
      path: '/locations/naples'
      fullPath: '/locations/naples'
      preLoaderRoute: typeof LocationsNaplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/orlando': {
      id: '/locations/orlando'
      path: '/locations/orlando'
      fullPath: '/locations/orlando'
      preLoaderRoute: typeof LocationsOrlandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/pensacola': {
      id: '/locations/pensacola'
      path: '/locations/pensacola'
      fullPath: '/locations/pensacola'
      preLoaderRoute: typeof LocationsPensacolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/tampa': {
      id: '/locations/tampa'
      path: '/locations/tampa'
      fullPath: '/locations/tampa'
      preLoaderRoute: typeof LocationsTampaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/west-palm-beach': {
      id: '/locations/west-palm-beach'
      path: '/locations/west-palm-beach'
      fullPath: '/locations/west-palm-beach'
      preLoaderRoute: typeof LocationsWestPalmBeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-services/': {
      id: '/professional-services/'
      path: '/professional-services'
      fullPath: '/professional-services/'
      preLoaderRoute: typeof ProfessionalServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-services/appraisal': {
      id: '/professional-services/appraisal'
      path: '/professional-services/appraisal'
      fullPath: '/professional-services/appraisal'
      preLoaderRoute: typeof ProfessionalServicesAppraisalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-services/expert-witness': {
      id: '/professional-services/expert-witness'
      path: '/professional-services/expert-witness'
      fullPath: '/professional-services/expert-witness'
      preLoaderRoute: typeof ProfessionalServicesExpertWitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-services/umpire': {
      id: '/professional-services/umpire'
      path: '/professional-services/umpire'
      fullPath: '/professional-services/umpire'
      preLoaderRoute: typeof ProfessionalServicesUmpireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$category': {
      id: '/blog/category/$category'
      path: '/category/$category'
      fullPath: '/blog/category/$category'
      preLoaderRoute: typeof BlogCategoryCategoryRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/page/2': {
      id: '/blog/page/2'
      path: '/page/2'
      fullPath: '/blog/page/2'
      preLoaderRoute: typeof BlogPage2RouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/page/3': {
      id: '/blog/page/3'
      path: '/page/3'
      fullPath: '/blog/page/3'
      preLoaderRoute: typeof BlogPage3RouteImport
      parentRoute: typeof BlogRoute
    }
    '/fr/locations/': {
      id: '/fr/locations/'
      path: '/locations'
      fullPath: '/fr/locations/'
      preLoaderRoute: typeof FrLocationsIndexRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/locations/fort-lauderdale': {
      id: '/fr/locations/fort-lauderdale'
      path: '/locations/fort-lauderdale'
      fullPath: '/fr/locations/fort-lauderdale'
      preLoaderRoute: typeof FrLocationsFortLauderdaleRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/locations/miami': {
      id: '/fr/locations/miami'
      path: '/locations/miami'
      fullPath: '/fr/locations/miami'
      preLoaderRoute: typeof FrLocationsMiamiRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/locations/naples': {
      id: '/fr/locations/naples'
      path: '/locations/naples'
      fullPath: '/fr/locations/naples'
      preLoaderRoute: typeof FrLocationsNaplesRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/locations/orlando': {
      id: '/fr/locations/orlando'
      path: '/locations/orlando'
      fullPath: '/fr/locations/orlando'
      preLoaderRoute: typeof FrLocationsOrlandoRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/locations/pensacola': {
      id: '/fr/locations/pensacola'
      path: '/locations/pensacola'
      fullPath: '/fr/locations/pensacola'
      preLoaderRoute: typeof FrLocationsPensacolaRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/locations/tampa': {
      id: '/fr/locations/tampa'
      path: '/locations/tampa'
      fullPath: '/fr/locations/tampa'
      preLoaderRoute: typeof FrLocationsTampaRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/locations/west-palm-beach': {
      id: '/fr/locations/west-palm-beach'
      path: '/locations/west-palm-beach'
      fullPath: '/fr/locations/west-palm-beach'
      preLoaderRoute: typeof FrLocationsWestPalmBeachRouteImport
      parentRoute: typeof FrRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogCategoryCategoryRoute: typeof BlogCategoryCategoryRoute
  BlogPage2Route: typeof BlogPage2Route
  BlogPage3Route: typeof BlogPage3Route
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogCategoryCategoryRoute: BlogCategoryCategoryRoute,
  BlogPage2Route: BlogPage2Route,
  BlogPage3Route: BlogPage3Route,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface FrRouteChildren {
  FrAboutRoute: typeof FrAboutRoute
  FrBlogRoute: typeof FrBlogRoute
  FrClaimsRoute: typeof FrClaimsRoute
  FrContactRoute: typeof FrContactRoute
  FrPrivacyRoute: typeof FrPrivacyRoute
  FrServicesRoute: typeof FrServicesRoute
  FrTermsRoute: typeof FrTermsRoute
  FrLocationsFortLauderdaleRoute: typeof FrLocationsFortLauderdaleRoute
  FrLocationsMiamiRoute: typeof FrLocationsMiamiRoute
  FrLocationsNaplesRoute: typeof FrLocationsNaplesRoute
  FrLocationsOrlandoRoute: typeof FrLocationsOrlandoRoute
  FrLocationsPensacolaRoute: typeof FrLocationsPensacolaRoute
  FrLocationsTampaRoute: typeof FrLocationsTampaRoute
  FrLocationsWestPalmBeachRoute: typeof FrLocationsWestPalmBeachRoute
  FrLocationsIndexRoute: typeof FrLocationsIndexRoute
}

const FrRouteChildren: FrRouteChildren = {
  FrAboutRoute: FrAboutRoute,
  FrBlogRoute: FrBlogRoute,
  FrClaimsRoute: FrClaimsRoute,
  FrContactRoute: FrContactRoute,
  FrPrivacyRoute: FrPrivacyRoute,
  FrServicesRoute: FrServicesRoute,
  FrTermsRoute: FrTermsRoute,
  FrLocationsFortLauderdaleRoute: FrLocationsFortLauderdaleRoute,
  FrLocationsMiamiRoute: FrLocationsMiamiRoute,
  FrLocationsNaplesRoute: FrLocationsNaplesRoute,
  FrLocationsOrlandoRoute: FrLocationsOrlandoRoute,
  FrLocationsPensacolaRoute: FrLocationsPensacolaRoute,
  FrLocationsTampaRoute: FrLocationsTampaRoute,
  FrLocationsWestPalmBeachRoute: FrLocationsWestPalmBeachRoute,
  FrLocationsIndexRoute: FrLocationsIndexRoute,
}

const FrRouteWithChildren = FrRoute._addFileChildren(FrRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ClaimsRoute: ClaimsRoute,
  ContactRoute: ContactRoute,
  FrRoute: FrRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  LocationsFortLauderdaleRoute: LocationsFortLauderdaleRoute,
  LocationsMiamiRoute: LocationsMiamiRoute,
  LocationsNaplesRoute: LocationsNaplesRoute,
  LocationsOrlandoRoute: LocationsOrlandoRoute,
  LocationsPensacolaRoute: LocationsPensacolaRoute,
  LocationsTampaRoute: LocationsTampaRoute,
  LocationsWestPalmBeachRoute: LocationsWestPalmBeachRoute,
  ProfessionalServicesAppraisalRoute: ProfessionalServicesAppraisalRoute,
  ProfessionalServicesExpertWitnessRoute:
    ProfessionalServicesExpertWitnessRoute,
  ProfessionalServicesUmpireRoute: ProfessionalServicesUmpireRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  ProfessionalServicesIndexRoute: ProfessionalServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
